# Generated by Django 4.2.17 on 2025-01-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Published'), (3, 'Archived')], default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('news', 'General News'), ('traffic', 'Traffic'), ('obituaries', 'Obituaries'), ('wedding', 'Wedding Announcements'), ('history', 'Village History'), ('achievements', 'Village Achievements')], default='news', max_length=50),
        ),
    ]
