# Generated by Django 4.2.17 on 2025-02-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='sources',
            field=models.TextField(blank=True, help_text='Optional: list any andall resources used in the article.'),
        ),
    ]
