# Generated by Django 4.2.17 on 2025-01-14 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_remove_article_is_published_article_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('content', models.TextField(help_text='The main content of the thread.')),
                ('related_article_url', models.URLField(blank=True, help_text='Optional: Paste the link to a related article.', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to=settings.AUTH_USER_MODEL)),
                ('related_article', models.ForeignKey(blank=True, help_text='Optional: Link this thread to an article.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_threads', to='news.article')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
