# Generated by Django 4.2.17 on 2025-01-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_thread_related_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='content',
        ),
        migrations.AddField(
            model_name='thread',
            name='description',
            field=models.TextField(default='Add your thread description here'),
        ),
    ]
