# Generated by Django 4.2.17 on 2025-01-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_thread_content_thread_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='approved',
        ),
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default='Add your thread description here', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1),
        ),
    ]
