# Generated by Django 4.2.17 on 2025-01-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_thread_approved_thread_slug_thread_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
