# Generated by Django 4.2.17 on 2025-01-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reported',
        ),
    ]
